### PR TITLE
You should totally add repo-wide diff

### PR DESCRIPTION
**Pull request by JHufstetlerGH**
do it do it do it

### CODE REVIEW

**Comment by mbinic** [comment]
Hehehe, thanks for the PR @JHufstetlerGH, loving your energy! :) I'll try it out and merge+release asap.

As for the naming, TortoiseGit menus show it as just "Diff", while the window it spawns is titled "Working Tree". I'm all for consistency, and `git diff` outputs a unified diff, so I'm not too afraid that calling it just "Diff" would create ambiguities. On the other hand, the other one is more in the spirit of TGit... What do you think?

Also, we haven't chosen a shortcut key for it. Ctrl+ G, Ctrl + D is available, cause File Diff uses more modifiers. Ctrl + G, Ctrl + W is available as well, should we choose the other name.

Since this extension is inspired by [TortoiseGitToolbar for Visual Studio](https://github.com/MRCollective/TortoiseGitToolbar) - @MattDavies, is this functionality something you'd like to see in your extension as well? What's your take on the naming?

**Comment by JHufstetlerGH** [comment]
I kinda prefer the way I named it (assuming you don't want to change command names and break peoples' custom key bindings).

### Confusing (command/title mismatch):
| Thing     | Command         | Title                 |
|-----------|-----------------|-----------------------|
| File Diff | `tgit.diff`     | TGit: File Diff       |
| Repo Diff | `tgit.diffRepo` | TGit: Diff |

### Somewhat Less Confusing:
| Thing     | Command         | Title                 |
|-----------|-----------------|-----------------------|
| File Diff | `tgit.diff`     | TGit: File Diff       |
| Repo Diff | `tgit.diffRepo` | TGit: Repository Diff |


I vote Ctrl+G, W if you want to add a hotkey, since that seems to follow a pattern:
| Extension           | Commit              | Repo Diff           |
|---------------------|---------------------|---------------------|
| TGit                | Ctrl+Shift+Alt+G, C | Ctrl+Shift+Alt+G, W |
| TortoiseGit Toolbar | Ctrl+G, C           | (what should go here?)              |

**Comment by MattDavies** [comment]
Hey, thanks for looping me in! Great feature addition.

The suggestion of "File Diff" / "Repository Diff" naming makes sense to me. I do completely agree "Diff" isn't likely to create ambiguity for most, but I think being very specific helps users unfamiliar with git. I'll happily adopt whichever approach this repository does in order to stay consistent.

**Comment by mbinic** [comment]
Thank you both for your input. The change is now on master and I'll release 1.3.0 this evening.
I've decided to retain the names, added a default key binding (G, D), and set Repo Diff as fallback for File Diff.

**Pull request closed without merging**
